### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by benstadin** [zeromq/dafka#62]
This looks really interesting. Though is this project actively maintained?

**Comment by somdoron** [comment]
Yes, can you share more about the usage? Also, from language are you going to use it?

**Comment by benstadin** [comment]
Glad to hear that. I'm implementing a kind of collision detection and fence service (client facing interfaces are HTTP REST and Websocket) for realtime events in C++. Instances of the service need to communicate between another for replication and also kind of data querying (data is mostly kept in-memory due to realtime requirements). 

There are mainly two usage scenarios:
- Data querying indirected via Pub/Sub between instances
- Data forwarding to a persistence service

Dafka seems pretty new. How stable would you rate it at the moment?

**Comment by somdoron** [comment]
I would imagine not very stable, but it is based on zeromq with not a lot of code on top.

Anyway, if you would give it a chance that will be great and me @sappo would be able to help

**Comment by benstadin** [comment]
Thanks for answer. I'll give it a try.
