### ISSUE TITLE
dafka vs kafka protocols

### ISSUE THREAD

**Issue by AlexCuse** [zeromq/dafka#72]
Just found this today - looks pretty cool I've actually been looking for something like this awhile.    I have a set of go microservices that use 0mq for messaging currently, and I want to explore a bit how I could get some enhanced messaging capabilities without the need to introduce another container to my deployments for a broker.  

Trying to figure out where to start with getting go services connected and wondering how close to the kafka protocol spec dafka's is.  Don't know C at all but I know the 0mq go client uses CGO and imagine a similar client could be possible, but if the protocol is close enough it might be worth trying to develop a 'pure go' client by tweaking an existing kafka client (most likely sarama).

Sorry for such a vague question but figured you might have some ideas.

**Comment by AlexCuse** [comment]
Sorry I missed the 'drop in replacement' bit in the readme

**Comment by sappo** [comment]
Hi Alex,
we're not quite at the stage where it is a drop in replacement.


Alex Ullrich <notifications@github.com> schrieb am Mi., 3. März 2021, 19:44:

**Comment by sappo** [comment]
The protocol itself is simpler than the kafka protocol. I.e. no consumer
groups.

Kevin Sapper <kevinsapper88@gmail.com> schrieb am Mi., 3. März 2021, 19:57:
