### ISSUE TITLE
Problem: We actually do prefix topic matching

### ISSUE THREAD

**Issue by somdoron** [zeromq/dafka#9]
The question is, is that a feature or a bug...
I think it can be a feature.

So if a consumer subscribe to "H" and publisher publish "HELLO" consumer will actually get the message.

So we either add a postifx to every topic to terminate it, or leave as is.

If we are leaving this as is, we need to test that it is actually work as expected

**Comment by sappo** [comment]
Definitely a feature. If users like to avoid the issue they need to choose good topic names

**Comment by somdoron** [comment]
Great.
So we need to write some tests for it. To make sure the reliability works for that as well.
I think it should work out of the box.

**Comment by shashank-shark** [comment]
Any guides or examples for dafka?

**Comment by sappo** [comment]
@shashank-shark All the documentation is currently in the README.md. The most complete example currently is the consumer selftest https://github.com/zeromq/dafka#dafka_consumer---no-title-found.
I'm happy to answer your questions though. Simply open an issue for them.
